#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelBot
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="coxautobot")]
	public partial class CoxAutoBotDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CoxAutoBotDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["coxautobotConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CoxAutoBotDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoxAutoBotDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoxAutoBotDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoxAutoBotDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTotalNumberCarsSold")]
		public int GetTotalNumberCarsSold([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalSold", DbType="Int")] ref System.Nullable<int> totalSold)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), totalSold);
			totalSold = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTopSellingModel")]
		public int GetTopSellingModel([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopSellingModel", DbType="VarChar(50)")] ref string topSellingModel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), topSellingModel);
			topSellingModel = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTopDealerCarsSold")]
		public int GetTopDealerCarsSold([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopDealerCarsSold", DbType="VarChar(50)")] ref string topDealerCarsSold)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), topDealerCarsSold);
			topDealerCarsSold = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTopDealerSpecificModelSold")]
		public int GetTopDealerSpecificModelSold([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarModel", DbType="VarChar(50)")] string carModel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopDealerCarsSold", DbType="VarChar(50)")] ref string topDealerCarsSold)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carModel, topDealerCarsSold);
			topDealerCarsSold = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTopModelForMakeSold")]
		public int GetTopModelForMakeSold([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarMake", DbType="VarChar(50)")] string carMake, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopModelSold", DbType="VarChar(50)")] ref string topModelSold)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carMake, topModelSold);
			topModelSold = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
